[package]
authors = ["Jaroslaw Weber<jaroslaw.weber@gmail.com>"]
name = "oxui"
version = "0.1.0"

[dependencies]
easer = "0.2.0"
find_folder = "0.3.0"
piston_window = "0.67.0"
serde_derive = "1.0.10"
serde_json = "1.0.2"
serde = "1.0.10"